#!/bin/bash
NUM=$(cat /etc/passwd | cut -d: -f3)
MIN="999"
MAX="2000"
 
echo "Lista de usuarios:"
for ID in do $NUM; do
    if [ $ID -gt $MIN > /dev/null 2>&1 ] && [ $ID -lt $MAX > /dev/null 2>&1 ] ; then
                USER=$(cat /etc/passwd | cut -d: -f1-3 | grep $ID | cut -d: -f1)
                echo "$USER"
        fi
done

#El 1 denota la salida estándar (stdout). El 2 denota el error estándar (stderr).Tan 2>&1 dice enviar error estándar a donde siempre es redirigido como salida estándar. Que desde se envía a /dev/null es similar a ignorar cualquier salida en absoluto.
